"""Exporters.

Board artefacts (03_quant_export/out/):
  yolo_desc.bin      descriptor table (relocated for DDR_BASE)
  yolo_weights.bin   all weight/param blobs (loaded at DDR_BASE + W_OFF)
  model_params.h     C header: DDR layout offsets, output scales, anchors, classes
  layout.json        same information for Python tools
Testbench artefacts (05_tb/data/<test>/):
  mem_init.hex       initial DDR image, 128-bit words (@addr records, zero words skipped)
  mem_exp.hex        expected DDR image after the run (golden descriptor simulator)
  test.cfg           "<base> <desc_addr> <num_layers> <words>" (hex)
usage: python export.py [image_path]
"""
import os, sys, json, pickle, glob
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..'))
sys.path.insert(0, os.path.join(ROOT, '02_golden_model'))
from darknet_parse import load_network, CLASSES
from float_model import load_image
from quant import int8_forward, input_q
from hwprog import yolo_program, feature_program, simulate, input_hwc16

DDR_BASE = 0x70000000


def write_hex(path, mem):
    words = mem.reshape(-1, 16)[:, ::-1]
    nz = np.flatnonzero(words.any(1))
    lines = []
    prev = -2
    hexrows = words[nz]
    for i, w in zip(nz, hexrows):
        if i != prev + 1:
            lines.append(f'@{i:x}')
        lines.append(w.tobytes().hex())
        prev = i
    with open(path, 'w') as f:
        f.write('\n'.join(lines) + '\n')


def export_tb(prog, name, input_hwc=None):
    d = os.path.join(ROOT, '05_tb', 'data', name)
    os.makedirs(d, exist_ok=True)
    mem0 = prog.ddr_image(input_hwc)
    mem1 = simulate(mem0.copy(), prog.base, prog.desc_addr, len(prog.layers))
    write_hex(os.path.join(d, 'mem_init.hex'), mem0)
    write_hex(os.path.join(d, 'mem_exp.hex'), mem1)
    words = len(mem0) // 16
    with open(os.path.join(d, 'test.cfg'), 'w') as f:
        f.write(f'{prog.base:08x} {prog.desc_addr:08x} {len(prog.layers):x} {words:x}\n')
    # region map for debugging mismatches
    with open(os.path.join(d, 'regions.txt'), 'w') as f:
        f.write(f'DESC {prog.desc_addr - prog.base:08x}\n')
        for b in prog.bufs:
            f.write(f'{b.name} {b.addr - prog.base:08x} {b.w} {b.h} {b.ch}\n')
        for L in prog.layers:
            f.write(f'W_{L.name} {L.w_addr - prog.base:08x}\n')
    print(f'  tb data {name}: {words} words ({len(mem0)/2**20:.2f} MiB), {len(prog.layers)} layers -> {d}')
    return mem1


def export_board(prog, q, net):
    out = os.path.join(HERE, 'out')
    os.makedirs(out, exist_ok=True)
    open(os.path.join(out, 'yolo_desc.bin'), 'wb').write(prog.descriptors())
    blob = b''.join(L.blob() for L in prog.layers)
    wimg = prog.ddr_image()[prog.w_base - prog.base:]
    open(os.path.join(out, 'yolo_weights.bin'), 'wb').write(wimg.tobytes())
    B = {b.name: b for b in prog.bufs}
    heads = []
    for (b, nc), lid in zip(prog.outputs, (29, 36)):
        yl = net['layers'][lid + 1]
        heads.append(dict(buf=b.name, off=b.addr - prog.base, w=b.w, h=b.h, pix=b.ch, ch=nc,
                          scale=float(q[lid]['s_out']), anchors=yl['anchors'], scale_x_y=yl['scale_x_y']))
    lay = dict(ddr_base=prog.base, total_bytes=prog.end - prog.base, desc_off=prog.desc_addr - prog.base,
               num_layers=len(prog.layers), in_off=B['IN'].addr - prog.base, in_w=416, in_h=416, in_pix=16,
               w_off=prog.w_base - prog.base, w_bytes=len(wimg), heads=heads, classes=CLASSES,
               input_shift=1, layers=[dict(lid=L.lid, w_off=L.w_addr - prog.base) for L in prog.layers])
    json.dump(lay, open(os.path.join(out, 'layout.json'), 'w'), indent=1)
    h = ['/* generated by 03_quant_export/export.py - do not edit */', '#ifndef MODEL_PARAMS_H', '#define MODEL_PARAMS_H',
         f'#define DDR_BASE        0x{prog.base:08X}u', f'#define DDR_BYTES       0x{lay["total_bytes"]:08X}u',
         f'#define DESC_OFF        0x{lay["desc_off"]:08X}u', f'#define NUM_LAYERS      {len(prog.layers)}',
         f'#define IN_OFF          0x{lay["in_off"]:08X}u', '#define IN_W 416', '#define IN_H 416', '#define IN_PIX 16',
         f'#define W_OFF           0x{lay["w_off"]:08X}u', f'#define W_BYTES         {len(wimg)}u',
         f'#define NUM_CLASSES     {len(CLASSES)}', '#define NUM_HEADS 2', '#define HEAD_PIX 64',
         'static const char *const CLASS_NAMES[NUM_CLASSES] __attribute__((unused)) = {' + ', '.join(f'"{c}"' for c in CLASSES) + '};',
         'typedef struct { unsigned off; int w, h; float scale; float scale_x_y; float anchors[3][2]; } head_t;',
         'static const head_t HEADS[NUM_HEADS] __attribute__((unused)) = {']
    for hd in heads:
        an = ', '.join(f'{{{a[0]}.f, {a[1]}.f}}' for a in hd['anchors'])
        h.append(f'  {{0x{hd["off"]:08X}u, {hd["w"]}, {hd["h"]}, {hd["scale"]:.9g}f, {hd["scale_x_y"]}f, {{{an}}}}},')
    h += ['};', '#endif']
    open(os.path.join(out, 'model_params.h'), 'w').write('\n'.join(h) + '\n')
    print(f'  board: desc {len(prog.layers)*64} B, weights {len(wimg)/2**20:.2f} MiB, DDR {lay["total_bytes"]/2**20:.2f} MiB -> {out}')


def main():
    img = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, '01_dataset/images/valid/000000000074.jpg')
    net = load_network()
    q = pickle.load(open(os.path.join(ROOT, '02_golden_model/out/qparams.pkl'), 'rb'))['q']
    prog = yolo_program(net, q); prog.layout(DDR_BASE)
    export_board(prog, q, net)
    rgb, _ = load_image(img)
    mem = export_tb(prog, 'yolo', input_hwc16(rgb))
    # cross-check expected TB image against the independent int8 tensor model
    _, heads = int8_forward(net, q, input_q(rgb))
    for (L, hq), (b, nc) in zip(heads, prog.outputs):
        assert np.array_equal(prog.read_buf(mem, b, 0, nc), hq), b.name
    np.save(os.path.join(ROOT, '05_tb/data/yolo/input_rgb.npy'), rgb)
    # board self-test vectors: raw RGB input, raw head buffers (as DDR holds them), golden detections
    out = os.path.join(HERE, 'out')
    rgb.tofile(os.path.join(out, 'test_input_rgb.bin'))
    heads_raw = b''.join(mem[b.addr - prog.base:b.addr - prog.base + b.size].tobytes() for b, _ in prog.outputs)
    open(os.path.join(out, 'test_heads.bin'), 'wb').write(heads_raw)
    from yolo_decode import detect
    from quant import dequant_heads
    dets = detect(dequant_heads(net, q, heads), [L for L, _ in heads], thresh=0.25)
    with open(os.path.join(out, 'test_dets.txt'), 'w') as f:
        for x1, y1, x2, y2, s, c in sorted(dets, key=lambda d: (-d[4], d[5])):
            f.write(f'{CLASSES[c]} {s:.4f} {x1:.4f} {y1:.4f} {x2:.4f} {y2:.4f}\n')
    fp = feature_program(1); fp.layout(DDR_BASE)
    export_tb(fp, 'feature')
    print('export OK (yolo TB expectation == int8 tensor model)')


if __name__ == '__main__':
    main()
