# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_zynq_ps_0/system_zynq_ps_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_zynq_ps_0 || ORIG_REF_NAME==system_zynq_ps_0} -quiet] -quiet

# IP: bd/system/ip/system_yolo_accel_0/system_yolo_accel_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_yolo_accel_0 || ORIG_REF_NAME==system_yolo_accel_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_pl0_0/system_rst_pl0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_pl0_0 || ORIG_REF_NAME==system_rst_pl0_0} -quiet] -quiet

# IP: bd/system/ip/system_sc_ctrl_0/system_sc_ctrl_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sc_ctrl_0 || ORIG_REF_NAME==system_sc_ctrl_0} -quiet] -quiet

# Block Designs: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/bd_73a6.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/ip/ip_0/bd_73a6_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/ip/ip_1/bd_73a6_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/ip/ip_2/bd_73a6_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/ip/ip_3/bd_73a6_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/ip/ip_4/bd_73a6_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/ip/ip_5/bd_73a6_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/ip/ip_6/bd_73a6_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/ip/ip_7/bd_73a6_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/ip/ip_8/bd_73a6_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/ip/ip_9/bd_73a6_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/ip/ip_10/bd_73a6_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/ip/ip_11/bd_73a6_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/ip/ip_12/bd_73a6_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_sc_mem_0/system_sc_mem_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sc_mem_0 || ORIG_REF_NAME==system_sc_mem_0} -quiet] -quiet

# Block Designs: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/bd_0182.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/ip/ip_0/bd_0182_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/ip/ip_1/bd_0182_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/ip/ip_2/bd_0182_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/ip/ip_3/bd_0182_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/ip/ip_4/bd_0182_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/ip/ip_5/bd_0182_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/ip/ip_6/bd_0182_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/ip/ip_7/bd_0182_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/ip/ip_8/bd_0182_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/ip/ip_9/bd_0182_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/ip/ip_10/bd_0182_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/ip/ip_11/bd_0182_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/ip/ip_12/bd_0182_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_zynq_ps_0/system_zynq_ps_0_ooc.xdc

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_zynq_ps_0/system_zynq_ps_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_zynq_ps_0 || ORIG_REF_NAME==system_zynq_ps_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_rst_pl0_0/system_rst_pl0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_pl0_0 || ORIG_REF_NAME==system_rst_pl0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_rst_pl0_0/system_rst_pl0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_pl0_0 || ORIG_REF_NAME==system_rst_pl0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/ip/ip_1/bd_73a6_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/ip/ip_1/bd_73a6_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/ip/ip_5/bd_73a6_s00a2s_0_ooc.xdc

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/ip/ip_6/bd_73a6_sarn_0_ooc.xdc

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/ip/ip_6/bd_73a6_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/ip/ip_7/bd_73a6_srn_0_ooc.xdc

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/ip/ip_7/bd_73a6_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/ip/ip_8/bd_73a6_sawn_0_ooc.xdc

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/ip/ip_8/bd_73a6_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/ip/ip_9/bd_73a6_swn_0_ooc.xdc

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/ip/ip_9/bd_73a6_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/ip/ip_10/bd_73a6_sbn_0_ooc.xdc

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/ip/ip_10/bd_73a6_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/bd_0/ip/ip_11/bd_73a6_m00s2a_0_ooc.xdc

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/ooc.xdc

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_ctrl_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sc_ctrl_0 || ORIG_REF_NAME==system_sc_ctrl_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/ip/ip_1/bd_0182_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/ip/ip_1/bd_0182_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/ip/ip_5/bd_0182_s00a2s_0_ooc.xdc

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/ip/ip_6/bd_0182_sarn_0_ooc.xdc

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/ip/ip_6/bd_0182_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/ip/ip_7/bd_0182_srn_0_ooc.xdc

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/ip/ip_7/bd_0182_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/ip/ip_8/bd_0182_sawn_0_ooc.xdc

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/ip/ip_8/bd_0182_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/ip/ip_9/bd_0182_swn_0_ooc.xdc

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/ip/ip_9/bd_0182_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/ip/ip_10/bd_0182_sbn_0_ooc.xdc

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/ip/ip_10/bd_0182_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/bd_0/ip/ip_11/bd_0182_m00s2a_0_ooc.xdc

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/ooc.xdc

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/ip/system_sc_mem_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sc_mem_0 || ORIG_REF_NAME==system_sc_mem_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/MPSOC_YOLO/06_vivado/proj/yolo_zcu104.gen/sources_1/bd/system/system_ooc.xdc
