// Verilog-2001 wrapper for Vivado block-design module reference (generated from yolo_accel.sv).
// aclk has no fixed FREQ_HZ: IP integrator propagates the real pl_clk0 frequency (see 06_vivado/build.tcl).
// m_axi_awuser/aruser (tied 0) exist only so the 1-bit AxUSER of S_AXI_HP0_FPD has a matching width.
module yolo_accel_wrap (
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 aclk CLK" *)
  (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF s_axi:m_axi, ASSOCIATED_RESET aresetn" *)
  input  wire           aclk,
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 aresetn RST" *)
  (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
  input  wire           aresetn,
  input  wire [7:0]     s_axi_awaddr,
  input  wire           s_axi_awvalid,
  output wire           s_axi_awready,
  input  wire [31:0]    s_axi_wdata,
  input  wire [3:0]     s_axi_wstrb,
  input  wire           s_axi_wvalid,
  output wire           s_axi_wready,
  output wire [1:0]     s_axi_bresp,
  output wire           s_axi_bvalid,
  input  wire           s_axi_bready,
  input  wire [7:0]     s_axi_araddr,
  input  wire           s_axi_arvalid,
  output wire           s_axi_arready,
  output wire [31:0]    s_axi_rdata,
  output wire [1:0]     s_axi_rresp,
  output wire           s_axi_rvalid,
  input  wire           s_axi_rready,
  output wire [0:0]     m_axi_awid,
  output wire [31:0]    m_axi_awaddr,
  output wire [7:0]     m_axi_awlen,
  output wire [2:0]     m_axi_awsize,
  output wire [1:0]     m_axi_awburst,
  output wire           m_axi_awlock,
  output wire [3:0]     m_axi_awcache,
  output wire [2:0]     m_axi_awprot,
  output wire [3:0]     m_axi_awqos,
  output wire [0:0]     m_axi_awuser,
  output wire           m_axi_awvalid,
  input  wire           m_axi_awready,
  output wire [127:0]   m_axi_wdata,
  output wire [15:0]    m_axi_wstrb,
  output wire           m_axi_wlast,
  output wire           m_axi_wvalid,
  input  wire           m_axi_wready,
  input  wire [0:0]     m_axi_bid,
  input  wire [1:0]     m_axi_bresp,
  input  wire           m_axi_bvalid,
  output wire           m_axi_bready,
  output wire [0:0]     m_axi_arid,
  output wire [31:0]    m_axi_araddr,
  output wire [7:0]     m_axi_arlen,
  output wire [2:0]     m_axi_arsize,
  output wire [1:0]     m_axi_arburst,
  output wire           m_axi_arlock,
  output wire [3:0]     m_axi_arcache,
  output wire [2:0]     m_axi_arprot,
  output wire [3:0]     m_axi_arqos,
  output wire [0:0]     m_axi_aruser,
  output wire           m_axi_arvalid,
  input  wire           m_axi_arready,
  input  wire [0:0]     m_axi_rid,
  input  wire [127:0]   m_axi_rdata,
  input  wire [1:0]     m_axi_rresp,
  input  wire           m_axi_rlast,
  input  wire           m_axi_rvalid,
  output wire           m_axi_rready,
  (* X_INTERFACE_INFO = "xilinx.com:signal:interrupt:1.0 irq INTERRUPT" *)
  (* X_INTERFACE_PARAMETER = "SENSITIVITY LEVEL_HIGH" *)
  output wire           irq
);
  assign m_axi_awuser = 1'b0;
  assign m_axi_aruser = 1'b0;

  yolo_accel u_core (
    .clk(aclk),
    .rst_n(aresetn),
    .s_axi_awaddr(s_axi_awaddr),
    .s_axi_awvalid(s_axi_awvalid),
    .s_axi_awready(s_axi_awready),
    .s_axi_wdata(s_axi_wdata),
    .s_axi_wstrb(s_axi_wstrb),
    .s_axi_wvalid(s_axi_wvalid),
    .s_axi_wready(s_axi_wready),
    .s_axi_bresp(s_axi_bresp),
    .s_axi_bvalid(s_axi_bvalid),
    .s_axi_bready(s_axi_bready),
    .s_axi_araddr(s_axi_araddr),
    .s_axi_arvalid(s_axi_arvalid),
    .s_axi_arready(s_axi_arready),
    .s_axi_rdata(s_axi_rdata),
    .s_axi_rresp(s_axi_rresp),
    .s_axi_rvalid(s_axi_rvalid),
    .s_axi_rready(s_axi_rready),
    .m_axi_awid(m_axi_awid),
    .m_axi_awaddr(m_axi_awaddr),
    .m_axi_awlen(m_axi_awlen),
    .m_axi_awsize(m_axi_awsize),
    .m_axi_awburst(m_axi_awburst),
    .m_axi_awlock(m_axi_awlock),
    .m_axi_awcache(m_axi_awcache),
    .m_axi_awprot(m_axi_awprot),
    .m_axi_awqos(m_axi_awqos),
    .m_axi_awvalid(m_axi_awvalid),
    .m_axi_awready(m_axi_awready),
    .m_axi_wdata(m_axi_wdata),
    .m_axi_wstrb(m_axi_wstrb),
    .m_axi_wlast(m_axi_wlast),
    .m_axi_wvalid(m_axi_wvalid),
    .m_axi_wready(m_axi_wready),
    .m_axi_bid(m_axi_bid),
    .m_axi_bresp(m_axi_bresp),
    .m_axi_bvalid(m_axi_bvalid),
    .m_axi_bready(m_axi_bready),
    .m_axi_arid(m_axi_arid),
    .m_axi_araddr(m_axi_araddr),
    .m_axi_arlen(m_axi_arlen),
    .m_axi_arsize(m_axi_arsize),
    .m_axi_arburst(m_axi_arburst),
    .m_axi_arlock(m_axi_arlock),
    .m_axi_arcache(m_axi_arcache),
    .m_axi_arprot(m_axi_arprot),
    .m_axi_arqos(m_axi_arqos),
    .m_axi_arvalid(m_axi_arvalid),
    .m_axi_arready(m_axi_arready),
    .m_axi_rid(m_axi_rid),
    .m_axi_rdata(m_axi_rdata),
    .m_axi_rresp(m_axi_rresp),
    .m_axi_rlast(m_axi_rlast),
    .m_axi_rvalid(m_axi_rvalid),
    .m_axi_rready(m_axi_rready),
    .irq(irq)
  );
endmodule
